# This file contains the configuration data in TOML format.

[account]
login_id = "your_login_id"
password = "your_password"
customer_id = "your_customer_id"
customer_company_name = "Your Company Name"
customer_name = "Your Name"
customer_email = "your_email@example.com"

[setups]
service_id = "your_service_id"
service_menu_id = "your_service_menu_id"
next_monday1 = 1
next_tuesday1 = 2
next_wednesday1 = 3
next_thursday1 = 4
next_friday1 = 5
next_monday2 = 6
next_tuesday2 = 7
next_wednesday2 = 8
next_thursday2 = 9
next_friday2 = 10